java_binary(
    name = "get_candles",
    srcs = ["GetCandles.java"],
    deps = [
        "@maven//:io_fission_fission_java_core",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
    ],
)
