java_binary(
    name = "get_candles",
    srcs = ["GetCandles.java"],
    deps = [
        "@maven//:io.fission:fission-java-core",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
    ],
)
