load("//src/main/java/com/verlumen/tradestar/functions/fission:fission.bzl", "FISSION_DEPS")

java_binary(
    name = "get_candles",
    srcs = ["GetCandles.java"],
    main_class = "com.verlumen.tradestar.functions.fission.candles.GetCandles",
    deps = FISSION_DEPS + [],
)
